Do not apply attributes to lambda expressions
This was added to clang after clang 3.4. Current minimum supported
version of clang is 3.3.
https://github.com/Microsoft/clang/commit/4bfb063cae5d2dbe59778bbcd7fea4ca143c7743

Note that while CChainState::LoadBlockIndex is declared with
EXCLUSIVE_LOCKS_REQUIRED(cs_main), and InsertBlockIndex runs
AssertLockHeld against cs_main, a thread-safety-analysis warning will
be issued absent AssertLockHeld.

Example failure:
    validation.cpp:3820:85: error: expected body of lambda expression
        if (!blocktree.LoadBlockIndexGuts(consensus_params, [this](const uint256& hash) __attribute__((exclusive_locks_required(cs_main))) { return this->InsertBlockIndex(hash); }))
                                                                                        ^
    1 error generated.
https://travis-ci.org/Empact/bitcoin/jobs/468855360